// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: detail/detail.proto

package com.springboot.bookinfo.details.lib.detail;

public final class BookDetailProto {
  private BookDetailProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GetBookDetailRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GetBookDetailRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 productId = 1;</code>
     */
    long getProductId();
  }
  /**
   * Protobuf type {@code GetBookDetailRequest}
   */
  public  static final class GetBookDetailRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GetBookDetailRequest)
      GetBookDetailRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetBookDetailRequest.newBuilder() to construct.
    private GetBookDetailRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetBookDetailRequest() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GetBookDetailRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              productId_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.springboot.bookinfo.details.lib.detail.BookDetailProto.internal_static_GetBookDetailRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.springboot.bookinfo.details.lib.detail.BookDetailProto.internal_static_GetBookDetailRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.springboot.bookinfo.details.lib.detail.BookDetailProto.GetBookDetailRequest.class, com.springboot.bookinfo.details.lib.detail.BookDetailProto.GetBookDetailRequest.Builder.class);
    }

    public static final int PRODUCTID_FIELD_NUMBER = 1;
    private long productId_;
    /**
     * <code>int64 productId = 1;</code>
     */
    public long getProductId() {
      return productId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (productId_ != 0L) {
        output.writeInt64(1, productId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (productId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, productId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.springboot.bookinfo.details.lib.detail.BookDetailProto.GetBookDetailRequest)) {
        return super.equals(obj);
      }
      com.springboot.bookinfo.details.lib.detail.BookDetailProto.GetBookDetailRequest other = (com.springboot.bookinfo.details.lib.detail.BookDetailProto.GetBookDetailRequest) obj;

      if (getProductId()
          != other.getProductId()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PRODUCTID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getProductId());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.springboot.bookinfo.details.lib.detail.BookDetailProto.GetBookDetailRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.springboot.bookinfo.details.lib.detail.BookDetailProto.GetBookDetailRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.springboot.bookinfo.details.lib.detail.BookDetailProto.GetBookDetailRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.springboot.bookinfo.details.lib.detail.BookDetailProto.GetBookDetailRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.springboot.bookinfo.details.lib.detail.BookDetailProto.GetBookDetailRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.springboot.bookinfo.details.lib.detail.BookDetailProto.GetBookDetailRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.springboot.bookinfo.details.lib.detail.BookDetailProto.GetBookDetailRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.springboot.bookinfo.details.lib.detail.BookDetailProto.GetBookDetailRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.springboot.bookinfo.details.lib.detail.BookDetailProto.GetBookDetailRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.springboot.bookinfo.details.lib.detail.BookDetailProto.GetBookDetailRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.springboot.bookinfo.details.lib.detail.BookDetailProto.GetBookDetailRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.springboot.bookinfo.details.lib.detail.BookDetailProto.GetBookDetailRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.springboot.bookinfo.details.lib.detail.BookDetailProto.GetBookDetailRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GetBookDetailRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GetBookDetailRequest)
        com.springboot.bookinfo.details.lib.detail.BookDetailProto.GetBookDetailRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.springboot.bookinfo.details.lib.detail.BookDetailProto.internal_static_GetBookDetailRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.springboot.bookinfo.details.lib.detail.BookDetailProto.internal_static_GetBookDetailRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.springboot.bookinfo.details.lib.detail.BookDetailProto.GetBookDetailRequest.class, com.springboot.bookinfo.details.lib.detail.BookDetailProto.GetBookDetailRequest.Builder.class);
      }

      // Construct using com.springboot.bookinfo.details.lib.detail.BookDetailProto.GetBookDetailRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        productId_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.springboot.bookinfo.details.lib.detail.BookDetailProto.internal_static_GetBookDetailRequest_descriptor;
      }

      @java.lang.Override
      public com.springboot.bookinfo.details.lib.detail.BookDetailProto.GetBookDetailRequest getDefaultInstanceForType() {
        return com.springboot.bookinfo.details.lib.detail.BookDetailProto.GetBookDetailRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.springboot.bookinfo.details.lib.detail.BookDetailProto.GetBookDetailRequest build() {
        com.springboot.bookinfo.details.lib.detail.BookDetailProto.GetBookDetailRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.springboot.bookinfo.details.lib.detail.BookDetailProto.GetBookDetailRequest buildPartial() {
        com.springboot.bookinfo.details.lib.detail.BookDetailProto.GetBookDetailRequest result = new com.springboot.bookinfo.details.lib.detail.BookDetailProto.GetBookDetailRequest(this);
        result.productId_ = productId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.springboot.bookinfo.details.lib.detail.BookDetailProto.GetBookDetailRequest) {
          return mergeFrom((com.springboot.bookinfo.details.lib.detail.BookDetailProto.GetBookDetailRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.springboot.bookinfo.details.lib.detail.BookDetailProto.GetBookDetailRequest other) {
        if (other == com.springboot.bookinfo.details.lib.detail.BookDetailProto.GetBookDetailRequest.getDefaultInstance()) return this;
        if (other.getProductId() != 0L) {
          setProductId(other.getProductId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.springboot.bookinfo.details.lib.detail.BookDetailProto.GetBookDetailRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.springboot.bookinfo.details.lib.detail.BookDetailProto.GetBookDetailRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long productId_ ;
      /**
       * <code>int64 productId = 1;</code>
       */
      public long getProductId() {
        return productId_;
      }
      /**
       * <code>int64 productId = 1;</code>
       */
      public Builder setProductId(long value) {
        
        productId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 productId = 1;</code>
       */
      public Builder clearProductId() {
        
        productId_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:GetBookDetailRequest)
    }

    // @@protoc_insertion_point(class_scope:GetBookDetailRequest)
    private static final com.springboot.bookinfo.details.lib.detail.BookDetailProto.GetBookDetailRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.springboot.bookinfo.details.lib.detail.BookDetailProto.GetBookDetailRequest();
    }

    public static com.springboot.bookinfo.details.lib.detail.BookDetailProto.GetBookDetailRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetBookDetailRequest>
        PARSER = new com.google.protobuf.AbstractParser<GetBookDetailRequest>() {
      @java.lang.Override
      public GetBookDetailRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetBookDetailRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetBookDetailRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetBookDetailRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.springboot.bookinfo.details.lib.detail.BookDetailProto.GetBookDetailRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BookDetailOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BookDetail)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     */
    long getId();

    /**
     * <code>string author = 2;</code>
     */
    java.lang.String getAuthor();
    /**
     * <code>string author = 2;</code>
     */
    com.google.protobuf.ByteString
        getAuthorBytes();

    /**
     * <code>int32 year = 3;</code>
     */
    int getYear();

    /**
     * <code>string type = 4;</code>
     */
    java.lang.String getType();
    /**
     * <code>string type = 4;</code>
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    /**
     * <code>int32 pages = 5;</code>
     */
    int getPages();

    /**
     * <code>string publisher = 6;</code>
     */
    java.lang.String getPublisher();
    /**
     * <code>string publisher = 6;</code>
     */
    com.google.protobuf.ByteString
        getPublisherBytes();

    /**
     * <code>string language = 7;</code>
     */
    java.lang.String getLanguage();
    /**
     * <code>string language = 7;</code>
     */
    com.google.protobuf.ByteString
        getLanguageBytes();

    /**
     * <code>string isbn10 = 8;</code>
     */
    java.lang.String getIsbn10();
    /**
     * <code>string isbn10 = 8;</code>
     */
    com.google.protobuf.ByteString
        getIsbn10Bytes();

    /**
     * <code>string isbn13 = 9;</code>
     */
    java.lang.String getIsbn13();
    /**
     * <code>string isbn13 = 9;</code>
     */
    com.google.protobuf.ByteString
        getIsbn13Bytes();
  }
  /**
   * Protobuf type {@code BookDetail}
   */
  public  static final class BookDetail extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:BookDetail)
      BookDetailOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BookDetail.newBuilder() to construct.
    private BookDetail(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BookDetail() {
      author_ = "";
      type_ = "";
      publisher_ = "";
      language_ = "";
      isbn10_ = "";
      isbn13_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BookDetail(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              author_ = s;
              break;
            }
            case 24: {

              year_ = input.readInt32();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              type_ = s;
              break;
            }
            case 40: {

              pages_ = input.readInt32();
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              publisher_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              language_ = s;
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              isbn10_ = s;
              break;
            }
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();

              isbn13_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.springboot.bookinfo.details.lib.detail.BookDetailProto.internal_static_BookDetail_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.springboot.bookinfo.details.lib.detail.BookDetailProto.internal_static_BookDetail_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.springboot.bookinfo.details.lib.detail.BookDetailProto.BookDetail.class, com.springboot.bookinfo.details.lib.detail.BookDetailProto.BookDetail.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int AUTHOR_FIELD_NUMBER = 2;
    private volatile java.lang.Object author_;
    /**
     * <code>string author = 2;</code>
     */
    public java.lang.String getAuthor() {
      java.lang.Object ref = author_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        author_ = s;
        return s;
      }
    }
    /**
     * <code>string author = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAuthorBytes() {
      java.lang.Object ref = author_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        author_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int YEAR_FIELD_NUMBER = 3;
    private int year_;
    /**
     * <code>int32 year = 3;</code>
     */
    public int getYear() {
      return year_;
    }

    public static final int TYPE_FIELD_NUMBER = 4;
    private volatile java.lang.Object type_;
    /**
     * <code>string type = 4;</code>
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      }
    }
    /**
     * <code>string type = 4;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PAGES_FIELD_NUMBER = 5;
    private int pages_;
    /**
     * <code>int32 pages = 5;</code>
     */
    public int getPages() {
      return pages_;
    }

    public static final int PUBLISHER_FIELD_NUMBER = 6;
    private volatile java.lang.Object publisher_;
    /**
     * <code>string publisher = 6;</code>
     */
    public java.lang.String getPublisher() {
      java.lang.Object ref = publisher_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        publisher_ = s;
        return s;
      }
    }
    /**
     * <code>string publisher = 6;</code>
     */
    public com.google.protobuf.ByteString
        getPublisherBytes() {
      java.lang.Object ref = publisher_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        publisher_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LANGUAGE_FIELD_NUMBER = 7;
    private volatile java.lang.Object language_;
    /**
     * <code>string language = 7;</code>
     */
    public java.lang.String getLanguage() {
      java.lang.Object ref = language_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        language_ = s;
        return s;
      }
    }
    /**
     * <code>string language = 7;</code>
     */
    public com.google.protobuf.ByteString
        getLanguageBytes() {
      java.lang.Object ref = language_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        language_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ISBN10_FIELD_NUMBER = 8;
    private volatile java.lang.Object isbn10_;
    /**
     * <code>string isbn10 = 8;</code>
     */
    public java.lang.String getIsbn10() {
      java.lang.Object ref = isbn10_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        isbn10_ = s;
        return s;
      }
    }
    /**
     * <code>string isbn10 = 8;</code>
     */
    public com.google.protobuf.ByteString
        getIsbn10Bytes() {
      java.lang.Object ref = isbn10_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        isbn10_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ISBN13_FIELD_NUMBER = 9;
    private volatile java.lang.Object isbn13_;
    /**
     * <code>string isbn13 = 9;</code>
     */
    public java.lang.String getIsbn13() {
      java.lang.Object ref = isbn13_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        isbn13_ = s;
        return s;
      }
    }
    /**
     * <code>string isbn13 = 9;</code>
     */
    public com.google.protobuf.ByteString
        getIsbn13Bytes() {
      java.lang.Object ref = isbn13_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        isbn13_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (!getAuthorBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, author_);
      }
      if (year_ != 0) {
        output.writeInt32(3, year_);
      }
      if (!getTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, type_);
      }
      if (pages_ != 0) {
        output.writeInt32(5, pages_);
      }
      if (!getPublisherBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, publisher_);
      }
      if (!getLanguageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, language_);
      }
      if (!getIsbn10Bytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, isbn10_);
      }
      if (!getIsbn13Bytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, isbn13_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (!getAuthorBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, author_);
      }
      if (year_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, year_);
      }
      if (!getTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, type_);
      }
      if (pages_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, pages_);
      }
      if (!getPublisherBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, publisher_);
      }
      if (!getLanguageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, language_);
      }
      if (!getIsbn10Bytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, isbn10_);
      }
      if (!getIsbn13Bytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, isbn13_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.springboot.bookinfo.details.lib.detail.BookDetailProto.BookDetail)) {
        return super.equals(obj);
      }
      com.springboot.bookinfo.details.lib.detail.BookDetailProto.BookDetail other = (com.springboot.bookinfo.details.lib.detail.BookDetailProto.BookDetail) obj;

      if (getId()
          != other.getId()) return false;
      if (!getAuthor()
          .equals(other.getAuthor())) return false;
      if (getYear()
          != other.getYear()) return false;
      if (!getType()
          .equals(other.getType())) return false;
      if (getPages()
          != other.getPages()) return false;
      if (!getPublisher()
          .equals(other.getPublisher())) return false;
      if (!getLanguage()
          .equals(other.getLanguage())) return false;
      if (!getIsbn10()
          .equals(other.getIsbn10())) return false;
      if (!getIsbn13()
          .equals(other.getIsbn13())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + AUTHOR_FIELD_NUMBER;
      hash = (53 * hash) + getAuthor().hashCode();
      hash = (37 * hash) + YEAR_FIELD_NUMBER;
      hash = (53 * hash) + getYear();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType().hashCode();
      hash = (37 * hash) + PAGES_FIELD_NUMBER;
      hash = (53 * hash) + getPages();
      hash = (37 * hash) + PUBLISHER_FIELD_NUMBER;
      hash = (53 * hash) + getPublisher().hashCode();
      hash = (37 * hash) + LANGUAGE_FIELD_NUMBER;
      hash = (53 * hash) + getLanguage().hashCode();
      hash = (37 * hash) + ISBN10_FIELD_NUMBER;
      hash = (53 * hash) + getIsbn10().hashCode();
      hash = (37 * hash) + ISBN13_FIELD_NUMBER;
      hash = (53 * hash) + getIsbn13().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.springboot.bookinfo.details.lib.detail.BookDetailProto.BookDetail parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.springboot.bookinfo.details.lib.detail.BookDetailProto.BookDetail parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.springboot.bookinfo.details.lib.detail.BookDetailProto.BookDetail parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.springboot.bookinfo.details.lib.detail.BookDetailProto.BookDetail parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.springboot.bookinfo.details.lib.detail.BookDetailProto.BookDetail parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.springboot.bookinfo.details.lib.detail.BookDetailProto.BookDetail parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.springboot.bookinfo.details.lib.detail.BookDetailProto.BookDetail parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.springboot.bookinfo.details.lib.detail.BookDetailProto.BookDetail parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.springboot.bookinfo.details.lib.detail.BookDetailProto.BookDetail parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.springboot.bookinfo.details.lib.detail.BookDetailProto.BookDetail parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.springboot.bookinfo.details.lib.detail.BookDetailProto.BookDetail parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.springboot.bookinfo.details.lib.detail.BookDetailProto.BookDetail parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.springboot.bookinfo.details.lib.detail.BookDetailProto.BookDetail prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BookDetail}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BookDetail)
        com.springboot.bookinfo.details.lib.detail.BookDetailProto.BookDetailOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.springboot.bookinfo.details.lib.detail.BookDetailProto.internal_static_BookDetail_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.springboot.bookinfo.details.lib.detail.BookDetailProto.internal_static_BookDetail_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.springboot.bookinfo.details.lib.detail.BookDetailProto.BookDetail.class, com.springboot.bookinfo.details.lib.detail.BookDetailProto.BookDetail.Builder.class);
      }

      // Construct using com.springboot.bookinfo.details.lib.detail.BookDetailProto.BookDetail.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0L;

        author_ = "";

        year_ = 0;

        type_ = "";

        pages_ = 0;

        publisher_ = "";

        language_ = "";

        isbn10_ = "";

        isbn13_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.springboot.bookinfo.details.lib.detail.BookDetailProto.internal_static_BookDetail_descriptor;
      }

      @java.lang.Override
      public com.springboot.bookinfo.details.lib.detail.BookDetailProto.BookDetail getDefaultInstanceForType() {
        return com.springboot.bookinfo.details.lib.detail.BookDetailProto.BookDetail.getDefaultInstance();
      }

      @java.lang.Override
      public com.springboot.bookinfo.details.lib.detail.BookDetailProto.BookDetail build() {
        com.springboot.bookinfo.details.lib.detail.BookDetailProto.BookDetail result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.springboot.bookinfo.details.lib.detail.BookDetailProto.BookDetail buildPartial() {
        com.springboot.bookinfo.details.lib.detail.BookDetailProto.BookDetail result = new com.springboot.bookinfo.details.lib.detail.BookDetailProto.BookDetail(this);
        result.id_ = id_;
        result.author_ = author_;
        result.year_ = year_;
        result.type_ = type_;
        result.pages_ = pages_;
        result.publisher_ = publisher_;
        result.language_ = language_;
        result.isbn10_ = isbn10_;
        result.isbn13_ = isbn13_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.springboot.bookinfo.details.lib.detail.BookDetailProto.BookDetail) {
          return mergeFrom((com.springboot.bookinfo.details.lib.detail.BookDetailProto.BookDetail)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.springboot.bookinfo.details.lib.detail.BookDetailProto.BookDetail other) {
        if (other == com.springboot.bookinfo.details.lib.detail.BookDetailProto.BookDetail.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (!other.getAuthor().isEmpty()) {
          author_ = other.author_;
          onChanged();
        }
        if (other.getYear() != 0) {
          setYear(other.getYear());
        }
        if (!other.getType().isEmpty()) {
          type_ = other.type_;
          onChanged();
        }
        if (other.getPages() != 0) {
          setPages(other.getPages());
        }
        if (!other.getPublisher().isEmpty()) {
          publisher_ = other.publisher_;
          onChanged();
        }
        if (!other.getLanguage().isEmpty()) {
          language_ = other.language_;
          onChanged();
        }
        if (!other.getIsbn10().isEmpty()) {
          isbn10_ = other.isbn10_;
          onChanged();
        }
        if (!other.getIsbn13().isEmpty()) {
          isbn13_ = other.isbn13_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.springboot.bookinfo.details.lib.detail.BookDetailProto.BookDetail parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.springboot.bookinfo.details.lib.detail.BookDetailProto.BookDetail) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long id_ ;
      /**
       * <code>int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 1;</code>
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object author_ = "";
      /**
       * <code>string author = 2;</code>
       */
      public java.lang.String getAuthor() {
        java.lang.Object ref = author_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          author_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string author = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAuthorBytes() {
        java.lang.Object ref = author_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          author_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string author = 2;</code>
       */
      public Builder setAuthor(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        author_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string author = 2;</code>
       */
      public Builder clearAuthor() {
        
        author_ = getDefaultInstance().getAuthor();
        onChanged();
        return this;
      }
      /**
       * <code>string author = 2;</code>
       */
      public Builder setAuthorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        author_ = value;
        onChanged();
        return this;
      }

      private int year_ ;
      /**
       * <code>int32 year = 3;</code>
       */
      public int getYear() {
        return year_;
      }
      /**
       * <code>int32 year = 3;</code>
       */
      public Builder setYear(int value) {
        
        year_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 year = 3;</code>
       */
      public Builder clearYear() {
        
        year_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object type_ = "";
      /**
       * <code>string type = 4;</code>
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string type = 4;</code>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string type = 4;</code>
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string type = 4;</code>
       */
      public Builder clearType() {
        
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <code>string type = 4;</code>
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        type_ = value;
        onChanged();
        return this;
      }

      private int pages_ ;
      /**
       * <code>int32 pages = 5;</code>
       */
      public int getPages() {
        return pages_;
      }
      /**
       * <code>int32 pages = 5;</code>
       */
      public Builder setPages(int value) {
        
        pages_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 pages = 5;</code>
       */
      public Builder clearPages() {
        
        pages_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object publisher_ = "";
      /**
       * <code>string publisher = 6;</code>
       */
      public java.lang.String getPublisher() {
        java.lang.Object ref = publisher_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          publisher_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string publisher = 6;</code>
       */
      public com.google.protobuf.ByteString
          getPublisherBytes() {
        java.lang.Object ref = publisher_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          publisher_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string publisher = 6;</code>
       */
      public Builder setPublisher(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        publisher_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string publisher = 6;</code>
       */
      public Builder clearPublisher() {
        
        publisher_ = getDefaultInstance().getPublisher();
        onChanged();
        return this;
      }
      /**
       * <code>string publisher = 6;</code>
       */
      public Builder setPublisherBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        publisher_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object language_ = "";
      /**
       * <code>string language = 7;</code>
       */
      public java.lang.String getLanguage() {
        java.lang.Object ref = language_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          language_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string language = 7;</code>
       */
      public com.google.protobuf.ByteString
          getLanguageBytes() {
        java.lang.Object ref = language_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          language_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string language = 7;</code>
       */
      public Builder setLanguage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        language_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string language = 7;</code>
       */
      public Builder clearLanguage() {
        
        language_ = getDefaultInstance().getLanguage();
        onChanged();
        return this;
      }
      /**
       * <code>string language = 7;</code>
       */
      public Builder setLanguageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        language_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object isbn10_ = "";
      /**
       * <code>string isbn10 = 8;</code>
       */
      public java.lang.String getIsbn10() {
        java.lang.Object ref = isbn10_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          isbn10_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string isbn10 = 8;</code>
       */
      public com.google.protobuf.ByteString
          getIsbn10Bytes() {
        java.lang.Object ref = isbn10_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          isbn10_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string isbn10 = 8;</code>
       */
      public Builder setIsbn10(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        isbn10_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string isbn10 = 8;</code>
       */
      public Builder clearIsbn10() {
        
        isbn10_ = getDefaultInstance().getIsbn10();
        onChanged();
        return this;
      }
      /**
       * <code>string isbn10 = 8;</code>
       */
      public Builder setIsbn10Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        isbn10_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object isbn13_ = "";
      /**
       * <code>string isbn13 = 9;</code>
       */
      public java.lang.String getIsbn13() {
        java.lang.Object ref = isbn13_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          isbn13_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string isbn13 = 9;</code>
       */
      public com.google.protobuf.ByteString
          getIsbn13Bytes() {
        java.lang.Object ref = isbn13_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          isbn13_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string isbn13 = 9;</code>
       */
      public Builder setIsbn13(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        isbn13_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string isbn13 = 9;</code>
       */
      public Builder clearIsbn13() {
        
        isbn13_ = getDefaultInstance().getIsbn13();
        onChanged();
        return this;
      }
      /**
       * <code>string isbn13 = 9;</code>
       */
      public Builder setIsbn13Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        isbn13_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:BookDetail)
    }

    // @@protoc_insertion_point(class_scope:BookDetail)
    private static final com.springboot.bookinfo.details.lib.detail.BookDetailProto.BookDetail DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.springboot.bookinfo.details.lib.detail.BookDetailProto.BookDetail();
    }

    public static com.springboot.bookinfo.details.lib.detail.BookDetailProto.BookDetail getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BookDetail>
        PARSER = new com.google.protobuf.AbstractParser<BookDetail>() {
      @java.lang.Override
      public BookDetail parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BookDetail(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BookDetail> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BookDetail> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.springboot.bookinfo.details.lib.detail.BookDetailProto.BookDetail getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetBookDetailRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetBookDetailRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BookDetail_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BookDetail_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023detail/detail.proto\")\n\024GetBookDetailRe" +
      "quest\022\021\n\tproductId\030\001 \001(\003\"\230\001\n\nBookDetail\022" +
      "\n\n\002id\030\001 \001(\003\022\016\n\006author\030\002 \001(\t\022\014\n\004year\030\003 \001(" +
      "\005\022\014\n\004type\030\004 \001(\t\022\r\n\005pages\030\005 \001(\005\022\021\n\tpublis" +
      "her\030\006 \001(\t\022\020\n\010language\030\007 \001(\t\022\016\n\006isbn10\030\010 " +
      "\001(\t\022\016\n\006isbn13\030\t \001(\t2J\n\021BookDetailService" +
      "\0225\n\rGetBookDetail\022\025.GetBookDetailRequest" +
      "\032\013.BookDetail\"\000B=\n*com.springboot.bookin" +
      "fo.details.lib.detailB\017BookDetailProtob\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_GetBookDetailRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GetBookDetailRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetBookDetailRequest_descriptor,
        new java.lang.String[] { "ProductId", });
    internal_static_BookDetail_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_BookDetail_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BookDetail_descriptor,
        new java.lang.String[] { "Id", "Author", "Year", "Type", "Pages", "Publisher", "Language", "Isbn10", "Isbn13", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
